# Generated by Django 5.2.17 on 2026-09-17 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_appointment_status_notifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-slot__date', '-slot__time'], 'permissions': [('approve_appointment', 'Can approve appointment'), ('reject_appointment', 'Can reject appointment'), ('postpone_appointment', 'Can postpone appointment'), ('reschedule_appointment', 'Can reschedule appointment'), ('transfer_appointment', 'Can transfer appointment'), ('cancel_appointment', 'Can cancel appointment')]},
        ),
    ]
