# Generated by Django 5.2.17 on 2026-09-17 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_overview', 'Can view overview'), ('view_reports', 'Can view reports'), ('view_settings', 'Can view settings')]},
        ),
    ]
