# Generated by Django 5.2.17 on 2026-09-17 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_auditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-slot__date', '-slot__time'], 'permissions': [('view_booking', 'Can view booking'), ('book_appointment', 'Can book appointment'), ('approve_appointment', 'Can approve appointment'), ('reject_appointment', 'Can reject appointment'), ('postpone_appointment', 'Can postpone appointment'), ('reschedule_appointment', 'Can reschedule appointment'), ('transfer_appointment', 'Can transfer appointment'), ('cancel_appointment', 'Can cancel appointment')]},
        ),
    ]
